athena_database_name  = "stockops_sensor"
athena_workgroup_name = "siseon-sensor-workgroup"
sensor_bucket_name    = "stockops-sensor-data"
query_result_bucket   = "siseon-athena-query-results"
cluster_name          = "seoul-cluster"
ohio_cluster_name     = "ohio-cluster"
aws_account_id        = "448768137813"